export type Tier = 1 | 2 | 3;

export type Step = {
  title: string;
  body: string;
  /** Optional screenshot file under public/screenshots/ rendered next to this step. */
  screenshot?: string;
};

export type Guide = {
  slug: string;
  tier: Tier;
  title: string;
  /** One-line answer to "what does this page teach me to do?" */
  task: string;
  /** Two-three sentence intro at the top of the page, no marketing language. */
  intro: string;
  /** Hero screenshot displayed in the page header. */
  screenshot?: string;
  steps: Step[];
  tips?: string[];
  troubleshooting?: { problem: string; fix: string }[];
  related?: string[]; // slugs
};

export const guides: Guide[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 1 — the three things the app actually exists to do
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: "generate-ai-report",
    tier: 1,
    title: "Generate an AI report",
    task: "Turn the notes, photos, and voice memos you captured today into a structured site report.",
    intro:
      "The AI report generator reads every note attached to a draft and writes a daily site report — weather, workforce, materials, issues, next steps, and free-form sections. You stay on the Notes tab while you collect input, then tap one button to produce the report.",
    screenshot: "08-report-generation.png",
    steps: [
      {
        title: "Open the project and start a new report",
        body:
          "From the **Projects** tab, tap the project you're working on. On the project overview, tap **Reports**, then tap **+ New Report**. The app drops you straight into the new draft on the **Notes** tab.",
        screenshot: "03-projects-list.png",
      },
      {
        title: "Capture what happened on site",
        body:
          "Type into the **Add a note…** field and tap the orange **Add** button. Each tap appends a numbered row to the timeline. Tap the **paperclip** icon to attach a photo from the camera or library, or tap the **microphone** to record a voice note (it auto-transcribes).",
        screenshot: "07-notes.png",
      },
      {
        title: "Tap Generate / Update report",
        body:
          "When the timeline reflects the day, switch to the **Notes** tab if you're not already there and tap the orange **Generate report** button. The button changes to **Update report** after the first run — tap it again any time you add more notes.",
      },
      {
        title: "Wait for the report to stream in",
        body:
          "The app switches to the **Report** tab and renders skeleton placeholders while the AI fills in each section. Generation usually finishes in 5–15 seconds. Don't navigate away — backgrounding the app cancels the stream.",
      },
      {
        title: "Review the sections",
        body:
          "Scroll the Report tab to read the generated weather, workforce, materials, issues, next steps, and free-form cards. Anything you don't like can be edited inline (see [Edit a report manually](/guides/edit-report-manually)) or regenerated by adding a clarifying note and tapping **Update report** again.",
      },
      {
        title: "Finalize when you're happy",
        body:
          "Scroll to the bottom of the Report tab and tap **Finalize Report**. Confirm in the dialog. The draft becomes a saved report and moves out of the Drafts list.",
      },
    ],
    tips: [
      "Add the most important observation first — the AI weights early notes more heavily.",
      "Voice notes are transcribed before they're fed to the model. If a transcript is wrong, long-press the voice note card and tap **Edit transcript** before regenerating.",
      "There's no penalty for re-running. Each tap of **Update report** rewrites the whole document from the latest notes.",
    ],
    troubleshooting: [
      {
        problem: "**Generate report** button is disabled.",
        fix: "Add at least one note (text, photo, or voice). The CTA enables once the timeline is non-empty.",
      },
      {
        problem: "Report comes back empty or with mostly N/A.",
        fix: "Your notes were too sparse. Add specifics — weather, headcount, what work happened — then tap **Update report**.",
      },
      {
        problem: "Generation hangs on skeletons.",
        fix: "Pull down to refresh the Report tab. If the offline banner is up, the request was queued; reconnect and tap **Update report** again.",
      },
    ],
    related: ["edit-report-manually", "capture-notes-voice", "export-share-pdf"],
  },

  {
    slug: "export-share-pdf",
    tier: 1,
    title: "Export and share a PDF",
    task: "Render any finalized report to a print-ready PDF and send it to your client.",
    intro:
      "Every saved report can be exported as a PDF that's rendered server-side and previewed on the device. From the preview you can save it to Files, share it through the system share sheet, or open it in another app.",
    screenshot: "11-pdf.png",
    steps: [
      {
        title: "Open a finalized report",
        body:
          "From the project's **Reports** list, tap any report that isn't in the Drafts section. Drafts can't be exported — finalize them first via **Finalize Report**.",
      },
      {
        title: "Open the actions menu",
        body:
          "On the report detail screen, tap the **⋯** (more) icon in the top-right corner of the header. A sheet slides up with **View PDF**, **Save PDF**, **Share PDF**, and **Delete report**.",
      },
      {
        title: "Preview the PDF",
        body:
          "Tap **View PDF**. The app calls the PDF edge function, then opens an in-app preview. Pinch to zoom; swipe to flip pages. Tap **Open externally** at the bottom to hand off to the system PDF viewer.",
      },
      {
        title: "Save it to Files",
        body:
          "Back in the actions menu, tap **Save PDF**. iOS shows a **Files** picker — choose iCloud Drive, On My iPhone, or any provider. A **PDF Saved** modal confirms the destination; tap **Done** to dismiss.",
      },
      {
        title: "Share via the system share sheet",
        body:
          "From the actions menu, tap **Share PDF**. The native share sheet opens with Mail, Messages, AirDrop, WhatsApp, and any other share targets installed on the device. Pick one and send.",
      },
    ],
    tips: [
      "The PDF is regenerated every time you tap **View PDF** or **Share PDF** — edits made via per-card pencils are picked up immediately.",
      "If you only need a screenshot, use **View PDF** and screenshot from the in-app preview instead of saving.",
    ],
    troubleshooting: [
      {
        problem: "Preview shows a blank page or spinner forever.",
        fix: "The render edge function timed out or you're offline. Check the connection banner; if you're offline, the request is queued and will succeed once you reconnect.",
      },
      {
        problem: "**Share PDF** doesn't show my app of choice.",
        fix: "iOS limits the share sheet to apps that registered a PDF handler. Use **Save PDF** to drop the file in Files, then open it from there.",
      },
    ],
    related: ["browse-saved-reports", "edit-report-manually"],
  },

  {
    slug: "work-offline-sync",
    tier: 1,
    title: "Work offline and sync later",
    task: "Keep working when you have no signal — the app queues every change and pushes it when you're back online.",
    intro:
      "The app is local-first. Notes, photos, voice notes, projects, and report edits all write to a local SQLite database first and replicate to the server when a connection is available. You don't need to do anything special to enable this — just keep working.",
    screenshot: "13-offline.png",
    steps: [
      {
        title: "Watch the connection banner",
        body:
          "When the device loses connectivity, an **Offline** banner slides down from the top of the screen and stays visible. When you reconnect, it briefly flips to **Back online** and auto-hides after a few seconds.",
      },
      {
        title: "Keep working as normal",
        body:
          "Create projects, add notes, record voice notes, edit report cards. Every action lands in local storage immediately — the timeline updates with no spinner, and edits persist if you kill the app.",
      },
      {
        title: "Reconnect to flush the queue",
        body:
          "Once the device gets a signal back, the **Back online** banner appears and the queued mutations push automatically. There is no manual sync button — the queue drains in the background.",
      },
      {
        title: "Resolve a conflict if one appears",
        body:
          "If someone else edited the same report while you were offline, a **Conflict** banner appears at the top of the report. Tap **Keep mine** to overwrite the server with your local version, or **Use server** to discard your offline edits.",
      },
    ],
    tips: [
      "AI report generation needs a live connection — the **Generate report** button shows an inline notice when you're offline. Notes you added offline will be included as soon as you reconnect.",
      "The queue is durable. Killing the app or rebooting the phone won't lose pending writes.",
      "On a dev build you can simulate offline mode: tap your avatar → scroll to **Developer** → toggle **Force offline**.",
    ],
    troubleshooting: [
      {
        problem: "Notes I added offline aren't showing up on another device.",
        fix: "They only sync when the device that captured them is back online. Once the **Back online** banner shows, the second device's next pull will see them.",
      },
      {
        problem: "**Conflict** banner won't go away.",
        fix: "You must pick a side — tap **Keep mine** or **Use server**. The banner only clears once you resolve.",
      },
    ],
    related: ["capture-notes-voice", "manage-projects"],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 2 — substantial how-tos for everyday workflows
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: "manage-projects",
    tier: 2,
    title: "Create and manage projects",
    task: "Set up a new construction site, edit its details, or remove it.",
    intro:
      "Each project is one site. The Projects tab is the home screen — every report, member, and file lives under a project.",
    screenshot: "04-new-project.png",
    steps: [
      {
        title: "Create a new project",
        body:
          "On the **Projects** tab, tap **+ New Project** in the top-right. Fill in **Project name**, **Address**, and **Client name**. Scroll down and tap **Create Project**. The new project appears at the top of the list.",
      },
      {
        title: "Open a project",
        body:
          "Tap any row in the projects list. You land on the project overview, which shows the latest activity, a Reports tile, a Members tile, and a Files tile.",
        screenshot: "05-project-home.png",
      },
      {
        title: "Edit project details",
        body:
          "On the overview, tap the **pencil** icon in the header. Update the name, address, or client and tap **Save**. Edits sync automatically; if you're offline they're queued.",
      },
      {
        title: "Delete a project",
        body:
          "From the project overview, tap the **⋯** menu in the header and tap **Delete project**. Confirm in the destructive action sheet. Deletion is permanent.",
      },
    ],
    tips: [
      "**Address** and **Client name** appear on every PDF report header — get them right when you create the project.",
      "Pull down on the projects list to refresh.",
    ],
    related: ["collaborate-members", "manage-files"],
  },

  {
    slug: "capture-notes-voice",
    tier: 2,
    title: "Capture notes, photos, and voice notes",
    task: "Build the timeline of observations that will feed the AI report.",
    intro:
      "Notes are the raw input the AI reads. The Notes tab on a draft report is a single timeline that mixes text, photos, and voice — entries appear in the order you captured them.",
    screenshot: "07-notes.png",
    steps: [
      {
        title: "Open the Notes tab",
        body:
          "From within a draft report, tap the **Notes** tab at the top of the screen. New drafts open here by default.",
      },
      {
        title: "Add a text note",
        body:
          "Tap the **Add a note…** field at the bottom, type your observation, and tap the orange **Add** button. The note appears as a numbered row above with a timestamp.",
      },
      {
        title: "Attach a photo",
        body:
          "Tap the **paperclip** icon next to the composer. Choose **Camera** to take a new photo or **Photo Library** to pick an existing one. The photo appears as its own timeline row.",
      },
      {
        title: "Record a voice note",
        body:
          "Tap the **microphone** icon. The button switches to a **Stop** button and a waveform animates while you speak. Tap **Stop** when done. The audio uploads, the recording appears in the timeline, and a transcript fills in within ~30 seconds.",
      },
      {
        title: "Edit or delete a note",
        body:
          "Long-press any note to copy its text. To remove a note, swipe its row left and tap **Delete**. Voice notes show an **id** badge — tap it to copy the file id (useful when reporting issues).",
      },
    ],
    tips: [
      "Voice transcripts are editable. Tap a voice note card to expand it, then tap the **pencil** on the transcript.",
      "The orange **Add** button is the only one-tap commit — keep typing then **Add**, don't paste paragraphs (split them into separate notes for better AI output).",
    ],
    troubleshooting: [
      {
        problem: "Voice note shows **Transcribing…** forever.",
        fix: "You're offline. The audio is uploaded and transcribed once you reconnect. Pull-to-refresh the Notes tab after the **Back online** banner.",
      },
    ],
    related: ["generate-ai-report", "work-offline-sync"],
  },

  {
    slug: "collaborate-members",
    tier: 2,
    title: "Add members to a project",
    task: "Share a project with teammates and pick what they can do.",
    intro:
      "Projects are private to their creator until you add members. Members are invited by phone number and assigned a role; access is enforced server-side.",
    screenshot: "06-members.png",
    steps: [
      {
        title: "Open the Members screen",
        body:
          "From a project overview, tap the **Members** tile (or the people icon in the header). The members list shows everyone with access plus their role.",
      },
      {
        title: "Add a member",
        body:
          "Tap **+ Add Member**. In the modal, enter the **Phone number** with country code (e.g. `+15559876543`). Pick a role: **Owner**, **Editor**, or **Viewer**. Tap **Add**.",
      },
      {
        title: "Change a member's role",
        body:
          "Tap a member's row. Pick a different role from the action sheet. The change applies immediately.",
      },
      {
        title: "Remove a member",
        body:
          "Tap a member's row, then tap **Remove from project** in the action sheet. Confirm. The member loses access to all reports and files for this project.",
      },
    ],
    tips: [
      "**Editor** can write notes and edit reports. **Viewer** is read-only. **Owner** can delete the project and manage other members.",
      "Members must already have a Haru 3 account on that phone number — invitations don't send SMS yet.",
    ],
    troubleshooting: [
      {
        problem: "**Add Member** shows _phone number with country code_ error.",
        fix: "Add the leading `+` and country code (e.g. `+1` for US). Local-format numbers are rejected.",
      },
    ],
    related: ["manage-projects"],
  },

  {
    slug: "manage-files",
    tier: 2,
    title: "Browse project files",
    task: "Find every photo and document attached to a project, in one grid.",
    intro:
      "Files is the per-project gallery. Anything attached as a photo note, plus any document uploaded directly, shows up here grouped by date.",
    screenshot: "12-files.png",
    steps: [
      {
        title: "Open Files",
        body:
          "From the project overview, tap the **Files** tile. The grid renders thumbnails grouped by capture date with newest on top.",
      },
      {
        title: "Preview a file",
        body:
          "Tap any thumbnail. Photos open in a full-screen lightbox — pinch to zoom, swipe to flip, tap once to show/hide chrome. Documents open in the system viewer.",
      },
      {
        title: "Delete a file",
        body:
          "Inside the preview, tap **⋯** in the header, then **Delete**. Confirm. Deletion is soft — admins can restore via the dashboard.",
      },
      {
        title: "Add a file directly",
        body:
          "From the Files screen, tap **+ Add**. Pick **Take Photo**, **Photo Library**, or **Document**. The file uploads in the background.",
      },
    ],
    tips: [
      "Photos attached as voice/note attachments appear here automatically — you don't need to upload them separately.",
      "The grid is offline-aware. Thumbnails were cached at upload time, so you won't see a **Downloading** flash.",
    ],
    related: ["capture-notes-voice"],
  },

  {
    slug: "edit-report-manually",
    tier: 2,
    title: "Edit a report manually",
    task: "Fix a single card on a generated or saved report — no global edit mode.",
    intro:
      "Every card on a report (Weather, Workforce, Materials, Issues, Next Steps, free-form sections) has its own edit affordance. Edits autosave in the background — there's no global Save button.",
    screenshot: "09-report-edit.png",
    steps: [
      {
        title: "Open the report",
        body:
          "Open a draft from the Drafts list, or a finalized report from the Reports list.",
      },
      {
        title: "Tap the pencil on a card",
        body:
          "Each card shows a small **pencil** icon in its top-right corner. Tap it. The card switches to edit mode — text fields become editable, list cards expose **+ Add row** and **×** delete affordances.",
      },
      {
        title: "Make your changes",
        body:
          "Edit the text fields directly. For list cards (Workforce, Materials, Issues, Next Steps), tap **+ Add row** to insert and the **×** at the end of any row to remove it.",
      },
      {
        title: "Commit or cancel",
        body:
          "Tap the green **✓** to commit the card edits, or the grey **✕** to discard them. Either way, the card flips back to read mode.",
      },
    ],
    tips: [
      "Even without tapping ✓, edits autosave 1.5 seconds after you stop typing, and again whenever the app backgrounds. The ✓ is mostly a convenience to flip back to read mode.",
      "If you edited a finalized report, the next **View PDF** / **Share PDF** will reflect your changes.",
    ],
    related: ["generate-ai-report", "browse-saved-reports"],
  },

  {
    slug: "browse-saved-reports",
    tier: 2,
    title: "Browse and reopen saved reports",
    task: "Find an old report, view it, edit it, or delete it.",
    intro:
      "Every finalized report stays accessible under the project's Reports list. You can read it, edit individual cards, export a PDF, or delete it.",
    screenshot: "10-saved-report.png",
    steps: [
      {
        title: "Open the Reports list",
        body:
          "From a project overview, tap the **Reports** tile. The list shows **Drafts** (peach tint) at the top and finalized reports below, newest first.",
      },
      {
        title: "Open a report",
        body:
          "Tap any row. The report detail screen shows all cards, source notes, and linked files.",
      },
      {
        title: "Edit a card",
        body:
          "See [Edit a report manually](/guides/edit-report-manually) — same per-card pencil flow on saved reports as on drafts.",
      },
      {
        title: "Export or delete",
        body:
          "Tap **⋯** in the header → **View PDF** / **Save PDF** / **Share PDF** to export, or **Delete report** to remove. Deletes are permanent and confirmed via a destructive action sheet.",
      },
    ],
    related: ["export-share-pdf", "edit-report-manually"],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 3 — short, combined utility pages
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: "getting-started",
    tier: 3,
    title: "Getting started",
    task: "Sign in for the first time and finish onboarding.",
    intro:
      "First launch: sign in with your phone number, then fill in your profile. After that the app drops you on the Projects tab.",
    screenshot: "01-login.png",
    steps: [
      {
        title: "Enter your phone number",
        body:
          "On the login screen, type your number into the **Phone Number** field with country code (e.g. `+15551234567`). Tap **Send Code**.",
      },
      {
        title: "Enter the SMS code",
        body:
          "Check your messages for the 6-digit code. Type it into the **Verification Code** field and tap **Verify**. (Dev builds use a fixed test code — see your team's setup notes.)",
      },
      {
        title: "Complete onboarding",
        body:
          "On first sign-in only, the **Welcome** screen appears. Enter your **Full Name** and **Company Name**, then tap **Get Started**.",
      },
    ],
    tips: [
      "If you mistyped your number, tap **Use a different number** before requesting a new code.",
      "Already onboarded? You skip the Welcome screen on subsequent sign-ins.",
    ],
    related: ["your-account"],
  },

  {
    slug: "your-account",
    tier: 3,
    title: "Your account",
    task: "Update your profile, see usage, sign out.",
    intro:
      "Tap your avatar in the Projects header to open the profile screen. Everything about your account lives here.",
    steps: [
      {
        title: "Change your display name or photo",
        body:
          "Tap your avatar → **Edit Profile**. Change **Full Name** or tap the avatar to pick a new photo. Tap **Save**.",
      },
      {
        title: "Check usage",
        body:
          "From the profile screen, tap **Usage**. See AI tokens consumed and transcription minutes used in the current billing period.",
      },
      {
        title: "Change language",
        body:
          "Profile → **Language**. Pick a language; the UI re-renders immediately.",
      },
      {
        title: "Sign out",
        body:
          "Profile → scroll to the bottom → **Sign out**. Confirm. The next launch returns to the login screen.",
      },
    ],
    related: ["getting-started"],
  },
];

export const guidesBySlug = Object.fromEntries(
  guides.map((g) => [g.slug, g]),
);

export const tier1 = guides.filter((g) => g.tier === 1);
export const tier2 = guides.filter((g) => g.tier === 2);
export const tier3 = guides.filter((g) => g.tier === 3);
