export type Tier = 1 | 2 | 3;

export type Step = {
  title: string;
  body: string;
  /** Optional screenshot file under public/screenshots/ rendered next to this step. */
  screenshot?: string;
};

export type Guide = {
  slug: string;
  tier: Tier;
  title: string;
  /** One-line answer to "what does this page teach me to do?" */
  task: string;
  /** Two-three sentence intro at the top of the page, no marketing language. */
  intro: string;
  /** Hero screenshot displayed in the page header. */
  screenshot?: string;
  steps: Step[];
  tips?: string[];
  troubleshooting?: { problem: string; fix: string }[];
  related?: string[]; // slugs
};

export const guides: Guide[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 1 — the three things the app actually exists to do
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: "generate-ai-report",
    tier: 1,
    title: "Generate an AI report",
    task: "Turn the notes, photos, and voice memos you captured today into a structured site report.",
    intro:
      "The AI report generator reads every note attached to a draft and writes a daily site report — weather, workers, materials, issues, next steps, and free-form sections. You stay on the Notes tab while you collect input, then tap one button to produce the report.",
    screenshot: "08-report-generation.png",
    steps: [
      {
        title: "Open the project and start a new report",
        body:
          "From the **Projects** tab, tap the project you're working on. On the project overview, tap the **Reports** action row, then tap the **New report** card (subtitle _Start a draft for this project._). The app drops you straight into the new draft on the **Notes** tab.",
        screenshot: "03-projects-list.png",
      },
      {
        title: "Capture what happened on site",
        body:
          "Type into the **Type a site note...** field. While the field is empty you'll see separate inline **Photo** and **Voice** buttons next to the composer — tap **Photo** to attach an image from camera or library, or **Voice** to record a voice note (it auto-transcribes). As soon as you start typing, those collapse and an orange **Add** button appears; tap it to commit the text note as a numbered timeline row.",
        screenshot: "07-notes.png",
      },
      {
        title: "Tap Generate report (or Update report)",
        body:
          "When the timeline reflects the day, scroll to the bottom of the **Notes** tab and tap the orange **Generate report** button. After the first run the button changes label depending on state: **Update report (N new note(s))** when you've added notes since the last generation, or **Report up to date** (disabled) when there's nothing new to fold in. While generating it shows **Generating…**.",
      },
      {
        title: "Wait for the report to stream in",
        body:
          "The app switches to the **Report** tab and renders skeleton placeholders while the AI fills in each section. Generation usually finishes in 5–15 seconds. Don't navigate away — backgrounding the app cancels the stream.",
      },
      {
        title: "Review the sections",
        body:
          "Scroll the Report tab to read the generated weather, workers, materials, issues, next steps, and free-form cards. Anything you don't like can be edited in the Edit tab (see [Edit a report manually](/guides/edit-report-manually)) or regenerated by adding a clarifying note and tapping **Update report** again.",
      },
      {
        title: "Finalize when you're happy",
        body:
          "Scroll to the bottom of the Report tab and tap **Finalize Report**. Confirm in the dialog. The draft becomes a saved report.",
      },
    ],
    tips: [
      "There's no penalty for re-running. Each tap of **Update report** rewrites the whole document from the latest notes.",
      "If a voice transcript is wrong, long-press the voice note to copy the transcript text — then add a corrected text note before regenerating.",
    ],
    troubleshooting: [
      {
        problem: "**Generate report** button is missing.",
        fix: "The timeline is empty. Add at least one note (text, photo, or voice) and the button appears at the bottom of the Notes tab.",
      },
      {
        problem: "Button says **Report up to date** and is disabled.",
        fix: "There are no new notes since the last generation. Add a note and the button flips back to **Update report (N new note(s))**.",
      },
      {
        problem: "Generation fails with an inline error above the skeletons.",
        fix: "The AI provider rejected the request — usually a transient network or rate-limit blip. Tap **Update report** again to retry. If it persists, the error text shown above the skeletons identifies the upstream cause.",
      },
      {
        problem: "Report comes back empty or with mostly N/A.",
        fix: "Your notes were too sparse. Add specifics — weather, headcount, what work happened — then tap **Update report**.",
      },
    ],
    related: ["edit-report-manually", "capture-notes-voice", "export-share-pdf"],
  },

  {
    slug: "export-share-pdf",
    tier: 1,
    title: "Export and share a PDF",
    task: "Render any finalized report to a print-ready PDF and send it to your client.",
    intro:
      "Every saved report can be exported as a PDF that's rendered server-side and previewed on the device. From the preview you can save it to the device, share it through the system share sheet, or open it in another app.",
    screenshot: "11-pdf.png",
    steps: [
      {
        title: "Open a finalized report",
        body:
          "From the project's **Reports** list, tap any report that isn't a draft. Drafts can't be exported — finalize them first via **Finalize Report**.",
      },
      {
        title: "Open the actions menu",
        body:
          "On the report detail screen, scroll to the **⋯ Actions** button (a labeled button below the header, not a top-right icon) and tap it. A sheet titled **Report Actions** slides up with **View PDF**, **Save PDF**, **Share PDF**, and **Delete Report**.",
      },
      {
        title: "Preview the PDF",
        body:
          "Tap **View PDF**. The app calls the PDF edge function, then opens an in-app preview titled **PDF Preview**. On iOS, tap **Share** in the top-right to hand off; on Android, tap **Open externally** at the bottom. Tap **Close** to dismiss the preview.",
      },
      {
        title: "Save it to the device",
        body:
          "Back in **Report Actions**, tap **Save PDF**. The file is written to the app's cache and a **PDF Saved** modal opens with three buttons: **Open PDF** (open in another app), **Share PDF** (system share sheet), and **Done** (dismiss).",
      },
      {
        title: "Share via the system share sheet",
        body:
          "From **Report Actions**, tap **Share PDF**. The native share sheet opens with Mail, Messages, AirDrop, WhatsApp, and any other share targets installed on the device. Pick one and send.",
      },
    ],
    tips: [
      "The PDF is regenerated every time you tap **View PDF**, **Save PDF**, or **Share PDF** — edits made in the Edit tab are picked up immediately.",
      "If you only need a screenshot, use **View PDF** and screenshot from the in-app preview instead of saving.",
    ],
    troubleshooting: [
      {
        problem: "Preview shows a blank page or spinner forever.",
        fix: "The render edge function timed out or you have no connection. Tap **Close** and retry **View PDF** — each tap regenerates the file from scratch, so a transient failure clears on retry.",
      },
      {
        problem: "Android: tapping **View PDF** does nothing or crashes.",
        fix: "Older builds offloaded PDF rendering to the system viewer; current builds render in-app via react-native-pdf. Make sure you're on a recent build — if a corporate MDM has stripped that module, **Open externally** still works.",
      },
      {
        problem: "Preview opens but is cut off at the top or bottom on a notched device.",
        fix: "Force-close and reopen the app — the modal uses safe-area insets that occasionally fail to hydrate on cold-launch. Reopening the report picks up the correct insets.",
      },
      {
        problem: "**Share PDF** doesn't show my app of choice.",
        fix: "iOS limits the share sheet to apps that registered a PDF handler. Use **Save PDF** then **Open PDF** from the confirmation modal to hand off via a different route.",
      },
    ],
    related: ["browse-saved-reports", "edit-report-manually"],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 2 — substantial how-tos for everyday workflows
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: "manage-projects",
    tier: 2,
    title: "Create and manage projects",
    task: "Set up a new construction site, edit its details, or remove it.",
    intro:
      "Each project is one site. The Projects tab is the home screen — every report and member lives under a project.",
    screenshot: "04-new-project.png",
    steps: [
      {
        title: "Create a new project",
        body:
          "On the **Projects** tab, tap the dashed **Add new project** card at the top of the list (or **Add your first project** if the list is empty). Fill in **Project Name**, **Project Address**, and **Client Name**. Tap **Create Project**. The new project appears in the list.",
      },
      {
        title: "Open a project",
        body:
          "Tap any row in the projects list. You land on the project overview, which shows **Total reports** and **Drafts** stat tiles, a **Last report** card, and four action rows: **Reports**, **Documents** (badged _Soon_), **Materials & Equipment** (_Soon_), and **Members**.",
        screenshot: "05-project-home.png",
      },
      {
        title: "Edit project details",
        body:
          "On the overview, tap the **pencil** icon next to the client name or address (in the body, not the header). Update **Project Name**, **Project Address**, or **Client Name** and tap **Save Changes**.",
      },
      {
        title: "Delete a project",
        body:
          "From the Edit Project screen, scroll to the bottom and tap the red **Delete Project** button. A **Delete Project** confirm dialog appears — tap **Delete** to confirm. Deletion is permanent.",
      },
    ],
    tips: [
      "**Project Address** and **Client Name** appear on every PDF report header — get them right when you create the project.",
      "Pull down on the projects list to refresh.",
    ],
    troubleshooting: [
      {
        problem: "Projects list shows a spinner forever after first sign-in.",
        fix: "The initial sync from the server is still running. Wait a few seconds — the list hydrates once the first pull completes. If it stays empty after a minute, pull down to force a refresh.",
      },
      {
        problem: "I created a project but it's missing on another device.",
        fix: "Pull down on the projects list on the second device to trigger a sync. Projects propagate via the sync engine, not push.",
      },
    ],
    related: ["collaborate-members"],
  },

  {
    slug: "capture-notes-voice",
    tier: 2,
    title: "Capture notes, photos, and voice notes",
    task: "Build the timeline of observations that will feed the AI report.",
    intro:
      "Notes are the raw input the AI reads. The Notes tab on a draft report is a single timeline that mixes text, photos, and voice — entries appear in the order you captured them.",
    screenshot: "07-notes.png",
    steps: [
      {
        title: "Open the Notes tab",
        body:
          "From within a draft report, tap the **Notes** tab at the top of the screen. New drafts open here by default.",
      },
      {
        title: "Add a text note",
        body:
          "Tap the **Type a site note…** field at the bottom and start typing. As soon as the field has content, the inline Photo/Voice buttons collapse and an orange **Add** button appears — tap it to commit. The note appears as a numbered row above with a timestamp.",
      },
      {
        title: "Attach a photo",
        body:
          "While the composer is empty, tap the inline **Photo** button next to it. Choose **Camera** to take a new photo or **Photo Library** to pick an existing one. The photo appears as its own timeline row.",
      },
      {
        title: "Record a voice note",
        body:
          "While the composer is empty, tap the inline **Voice** button. The button switches to a **Stop** button with a pulsing background while you speak. Tap **Stop** when done. The audio uploads, the recording appears in the timeline, and a transcript fills in within ~30 seconds.",
      },
      {
        title: "Copy a transcript or delete a note",
        body:
          "Long-press a **voice note** to copy its transcript (text notes don't support long-press). To remove any note, tap the **Trash** icon on its row. Voice notes ask for confirmation before deleting; text and photo notes delete immediately. Voice notes also show an **id** badge — tap it to copy the file id (useful when reporting issues).",
      },
    ],
    tips: [
      "Transcripts can't be edited in the app. If a transcript is wrong, long-press it to copy, then add a corrected text note.",
      "Split long observations into separate short notes — the AI handles many small notes better than one big block.",
    ],
    troubleshooting: [
      {
        problem: "Voice note shows **Transcribing…** forever.",
        fix: "The transcribe edge function is still working or the upload is in progress. Wait ~30s and pull-to-refresh the Notes tab. If it still hasn't completed, check your network — the transcript fills in automatically once the upload retries succeed.",
      },
      {
        problem: "Voice note plays once, then **Play** does nothing.",
        fix: "Older builds had a stuck-after-finish bug; recent builds reset playback automatically. Tap the note row again — if it still won't replay, navigate away from the Notes tab and back to remount the player.",
      },
      {
        problem: "Voice note disappears immediately after I finish recording.",
        fix: "Don't navigate away while a transcription is in flight on a slow network. The row is now persisted as soon as you stop recording, but on very old builds leaving the screen mid-upload could drop it. Re-record if it's missing.",
      },
      {
        problem: "Photo picker opens but the photo doesn't appear in the timeline.",
        fix: "On Android, grant CAMERA and Photos permissions in system Settings → Apps → Harpa Pro → Permissions, then retry. iOS prompts on first use.",
      },
    ],
    related: ["generate-ai-report"],
  },

  {
    slug: "collaborate-members",
    tier: 2,
    title: "Add members to a project",
    task: "Share a project with teammates and pick what they can do.",
    intro:
      "Projects are private to their creator until you add members. Members are invited by phone number and assigned a role; access is enforced server-side.",
    screenshot: "06-members.png",
    steps: [
      {
        title: "Open the Members screen",
        body:
          "From a project overview, tap the **Members** action row. The members list shows everyone with access plus their role. The header has a Back button only — there is no people icon.",
      },
      {
        title: "Add a member",
        body:
          "Tap the **Add member** card. In the modal, enter the **Phone number** with country code (e.g. `+15559876543`). Pick a role: **Admin**, **Editor**, or **Viewer** (the project's Owner role is auto-assigned to the creator and cannot be selected). Tap **Add Member**.",
      },
      {
        title: "Remove a member",
        body:
          "On the member's row, tap the **Trash** icon. A **Remove Member** confirm dialog appears — tap **Remove** to confirm. The member loses access to all reports for this project.",
      },
    ],
    tips: [
      "**Admin** can manage members and project settings. **Editor** can write notes and edit reports. **Viewer** is read-only. **Owner** is the creator and is set automatically.",
      "There's no in-app way to change an existing member's role yet — remove them and re-add with the new role.",
      "Members must already have a Harpa Pro account on that phone number — invitations don't send SMS yet.",
    ],
    troubleshooting: [
      {
        problem: "**Add Member** shows _phone number with country code_ error.",
        fix: "Add the leading `+` and country code (e.g. `+1` for US). Local-format numbers are rejected.",
      },
      {
        problem: "Member list doesn't refresh after I add someone on another device.",
        fix: "Pull down on the projects list to force a sync, then reopen Members. Member changes propagate when projects sync.",
      },
    ],
    related: ["manage-projects"],
  },

  {
    slug: "edit-report-manually",
    tier: 2,
    title: "Edit a report manually",
    task: "Override what the AI wrote on any saved report.",
    intro:
      "Every saved report has two tabs at the top: **Report** (read-only rendered view) and **Edit** (one big form covering every section). All sections are always editable in the Edit tab — there's no per-card pencil. Edits autosave in the background; there's no Save button.",
    screenshot: "09-report-edit.png",
    steps: [
      {
        title: "Open the report",
        body:
          "Open a draft from the Drafts list, or a finalized report from the Reports list.",
      },
      {
        title: "Switch to the Edit tab",
        body:
          "Tap the **Edit** tab at the top of the report screen. The whole report is replaced by an editable form covering Weather, Workers, Materials, Issues, Next Steps, and any free-form sections.",
      },
      {
        title: "Edit fields and rows",
        body:
          "Type directly into any field. For list sections, use **Add role** (Workers), **Add material** (Materials), **Add issue** (Issues), **Add next step** (Next Steps), or **Add section** (free-form). Each row has a **Remove** button (trash icon) that asks for confirmation before deleting.",
      },
      {
        title: "Switch back to Report when done",
        body:
          "Tap the **Report** tab to see your changes rendered. There is no explicit save action — autosave persists everything.",
      },
    ],
    tips: [
      "Autosave fires 1.5 seconds after you stop typing, and again whenever the app backgrounds. There is no Save button anywhere on the Edit tab.",
      "If you edited a finalized report, the next **View PDF** / **Share PDF** will reflect your changes.",
    ],
    troubleshooting: [
      {
        problem: "Edits I made on the Edit tab don't appear in the rendered Report tab.",
        fix: "Autosave debounces 1.5s after the last keystroke. Stop typing, wait two seconds, then tap **Report**. Backgrounding the app also flushes pending edits immediately.",
      },
      {
        problem: "Numeric or boolean field shows quoted text on the Report tab.",
        fix: "The schema stores all field values as strings. The Report tab renders them as written — type a plain number (e.g. `12`) without quotes.",
      },
    ],
    related: ["generate-ai-report", "browse-saved-reports"],
  },

  {
    slug: "browse-saved-reports",
    tier: 2,
    title: "Browse and reopen saved reports",
    task: "Find an old report, view it, edit it, or delete it.",
    intro:
      "Every report — draft and finalized — stays accessible under the project's Reports list. You can read it, edit it, export a PDF, or delete it.",
    screenshot: "10-saved-report.png",
    steps: [
      {
        title: "Open the Reports list",
        body:
          "From a project overview, tap the **Reports** action row. The list shows every report sorted by creation date (newest first). Drafts and finalized reports are interleaved by date — drafts are marked with a peach **DRAFT** badge and rendered with a cream off-white card background.",
      },
      {
        title: "Open a report",
        body:
          "Tap any finalized row to open the report detail screen with Report and Edit tabs. Tapping a **draft** row instead jumps you back into the report generator (Notes/Report tabs) so you can keep working on it.",
      },
      {
        title: "Edit",
        body:
          "See [Edit a report manually](/guides/edit-report-manually) — switch to the **Edit** tab on the detail screen.",
      },
      {
        title: "Export or delete",
        body:
          "Scroll to the **⋯ Actions** button to open the **Report Actions** sheet → **View PDF** / **Save PDF** / **Share PDF** to export, or **Delete Report** to remove. Deletes are permanent and confirmed via a destructive dialog.",
      },
    ],
    related: ["export-share-pdf", "edit-report-manually"],
    troubleshooting: [
      {
        problem: "I tapped a draft expecting the report detail screen but landed in the note generator.",
        fix: "By design — drafts open in the Notes/Report generator so you can keep working on them. Finalize the draft (**Finalize Report** at the bottom of the Report tab) to make it open the static detail screen instead.",
      },
      {
        problem: "Reports list is empty even though I created reports on another device.",
        fix: "Pull down on the list to force a sync, or pull down on the projects list one screen up. Reports sync per-user; signing in on a fresh device triggers a full pull on first load.",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 3 — short, combined utility pages
  // ─────────────────────────────────────────────────────────────────────────────
  {
    slug: "getting-started",
    tier: 3,
    title: "Getting started",
    task: "Sign in for the first time and finish onboarding.",
    intro:
      "First launch: sign in with your phone number, then fill in your profile. After that the app drops you on the Projects tab.",
    screenshot: "01-login.png",
    steps: [
      {
        title: "Enter your phone number",
        body:
          "On the login screen, type your number into the **Phone Number** field with country code (e.g. `+15551234567`). Tap **Send Code**. (Returning users on the same device may see a **Use a different number** link if a previous number is remembered — tap it to clear and re-enter.)",
      },
      {
        title: "Enter the SMS code",
        body:
          "Check your messages for the 6-digit code. Type it into the **Verification Code** field and tap **Verify Code**. If you mistyped your number, tap **Change Number** to go back. (Dev builds use a fixed test code — see your team's setup notes.)",
      },
      {
        title: "Complete onboarding",
        body:
          "On first sign-in only, the **Welcome** screen appears. Enter your **Full Name** and **Company Name**, then tap **Get Started**.",
        screenshot: "02-onboarding.png",
      },
    ],
    tips: [
      "Already onboarded? You skip the Welcome screen on subsequent sign-ins.",
    ],
    troubleshooting: [
      {
        problem: "Pressing **Send Code** does nothing or errors out.",
        fix: "The phone field needs `+` plus country code. `15551234567` without `+` is rejected; `+15551234567` works.",
      },
      {
        problem: "I never receive the SMS code.",
        fix: "Wait 30s and tap **Send Code** again. Some carriers throttle short-code SMS; if it still doesn't arrive, tap **Change Number** and re-enter to confirm there's no typo.",
      },
      {
        problem: "After signing out and signing in as a different user, I see the previous user's projects briefly.",
        fix: "Force-close and reopen the app. Recent builds clear the local SQLite file and React Query cache on sign-out, but a stale screen mid-transition can briefly render. The data layer reloads correctly once you reach Projects.",
      },
    ],
    related: ["your-account"],
  },

  {
    slug: "your-account",
    tier: 3,
    title: "Your account",
    task: "Update your profile photo, see usage, sign out.",
    intro:
      "Tap your avatar in the Projects header to open the profile screen. From there you can view account details, check AI usage, clear cached data, and sign out.",
    steps: [
      {
        title: "Change your profile photo",
        body:
          "From the profile screen, tap **Account Details**. Tap your avatar to pick a new photo — it uploads automatically with no Save button. **Full Name**, **Phone**, and **Company Name** are shown but cannot be edited from inside the app yet.",
      },
      {
        title: "Check usage",
        body:
          "From the profile screen, tap **Usage**. The page shows AI token usage broken down by **Reports**, **Input**, **Output**, and **Cached** for the current period.",
      },
      {
        title: "Sign out",
        body:
          "Profile → scroll to the bottom → **Sign out**. There is no confirmation dialog — the tap signs you out immediately and returns you to the login screen.",
      },
    ],
    tips: [
      "**Clear cached data** is also on the profile screen and _does_ show a confirm dialog before wiping. Don't confuse it with **Sign out**.",
    ],
    troubleshooting: [
      {
        problem: "Profile photo upload shows a spinner but never finishes.",
        fix: "Check your network — the photo uploads to storage in the background. Force-close the app and reopen the profile screen; if the photo is there, it succeeded silently. If not, tap the avatar again.",
      },
      {
        problem: "Usage page is empty or stuck on a loading shimmer.",
        fix: "Pull down on the page to refresh. The loading state is layout-stable, so an empty card means the API hasn't returned yet — give it a few seconds.",
      },
      {
        problem: "I want to change my Full Name or Company Name.",
        fix: "Not editable in-app yet — only the avatar is. Contact your team admin to update the underlying profile, or wait for a build that exposes the edit fields.",
      },
    ],
    related: ["getting-started"],
  },
];

export const guidesBySlug: Record<string, Guide> = Object.fromEntries(
  guides.map((g) => [g.slug, g]),
);

export const tier1: Guide[] = guides.filter((g) => g.tier === 1);
export const tier2: Guide[] = guides.filter((g) => g.tier === 2);
export const tier3: Guide[] = guides.filter((g) => g.tier === 3);
