/**
 * Typed testID registry for Maestro flows.
 *
 * Phase 0: Empty stubs. Features will fill in as implemented.
 */

export const testIds = {
  auth: {
    signInButton: "auth:sign-in-button",
    signUpButton: "auth:sign-up-button",
    phoneInput: "auth:phone-input",
    otpInput: "auth:otp-input",
    submitButton: "auth:submit-button",
    onboardingFullNameInput: "auth:onboarding-full-name-input",
    onboardingCompanyNameInput: "auth:onboarding-company-name-input",
    onboardingSubmitButton: "auth:onboarding-submit-button",
    callback: "auth:callback",
  },
  projects: {
    list: "projects:list",
    card: (id: string) => `projects:card:${id}`,
    createButton: "projects:create-button",
    form: {
      nameInput: "projects:form:name-input",
      addressInput: "projects:form:address-input",
      submitButton: "projects:form:submit-button",
    },
    overviewCard: "projects:overview-card",
    membersButton: "projects:members-button",
    reportsButton: "projects:reports-button",
    editButton: "projects:edit-button",
    deleteButton: "projects:delete-button",
    confirmDelete: "projects:confirm-delete",
    membersList: "projects:members-list",
    memberRow: (id: string) => `projects:member-row:${id}`,
    changeRoleButton: (id: string) => `projects:change-role-button:${id}`,
    removeMemberButton: (id: string) => `projects:remove-member-button:${id}`,
    confirmRemoveMember: "projects:confirm-remove-member",
    roleOption: (role: string) => `projects:role-option:${role}`,
    inviteMemberButton: "projects:invite-member-button",
    invitePhoneInput: "projects:invite-phone-input",
    inviteRoleOption: (role: string) => `projects:invite-role-option:${role}`,
    inviteSubmitButton: "projects:invite-submit-button",
  },
  reports: {
    list: "reports:list",
    card: (id: string) => `reports:card:${id}`,
    createButton: "reports:create-button",
    newReportTitleInput: "reports:new-report-title-input",
    createReportButton: "reports:create-report-button",
    tab: (tab: string) => `reports:tab:${tab}`,
    saveButton: "reports:save-button",
    deleteButton: "reports:delete-button",
    editSectionMeta: "reports:edit-section-meta",
    editSectionWeather: "reports:edit-section-weather",
    editSectionWorkers: "reports:edit-section-workers",
    editSectionMaterials: "reports:edit-section-materials",
    editSectionIssues: "reports:edit-section-issues",
    editFieldTitle: "reports:edit-field-title",
    addRoleButton: "reports:add-role-button",
    addMaterialButton: "reports:add-material-button",
    addIssueButton: "reports:add-issue-button",
  },
  notes: {
    timeline: "notes:timeline",
    addNoteInput: "notes:add-note-input",
    addNoteButton: "notes:add-note-button",
    addVoiceButton: "notes:add-voice-button",
    pendingPhoto: (localId: string) => `notes:pending-photo:${localId}`,
  },
  voiceNotes: {
    card: (id: string) => `voice-notes:card:${id}`,
    playButton: (id: string) => `voice-notes:play-button:${id}`,
    pauseButton: (id: string) => `voice-notes:pause-button:${id}`,
    progressBar: (id: string) => `voice-notes:progress-bar:${id}`,
    moreButton: (id: string) => `voice-notes:more-button:${id}`,
    deleteButton: (id: string) => `voice-notes:delete-button:${id}`,
    viewTranscriptButton: (id: string) =>
      `voice-notes:view-transcript-button:${id}`,
    transcriptSheet: (id: string) => `voice-notes:transcript-sheet:${id}`,
    transcriptText: (id: string) => `voice-notes:transcript-text:${id}`,
    deleteSheet: (id: string) => `voice-notes:delete-sheet:${id}`,
    title: (id: string) => `voice-notes:title:${id}`,
    summary: (id: string) => `voice-notes:summary:${id}`,
    recordButton: "voice-notes:record-button",
    recordingIndicator: "voice-notes:recording-indicator",
    levelMeter: "voice-notes:level-meter",
  },
  uploads: {
    pendingRow: (jobId: string) => `uploads:pending-row:${jobId}`,
    progress: (jobId: string) => `uploads:progress:${jobId}`,
    retryButton: (jobId: string) => `uploads:retry-button:${jobId}`,
    cancelButton: (jobId: string) => `uploads:cancel-button:${jobId}`,
  },
  camera: {
    screen: "camera:screen",
    captureButton: "camera:capture-button",
    closeButton: "camera:close-button",
    flipButton: "camera:flip-button",
    doneButton: "camera:done-button",
    requestPermissionButton: "camera:request-permission-button",
  },
  account: {
    screen: "account:screen",
    avatar: "account:avatar",
    name: "account:name",
    email: "account:email",
    company: "account:company",
    version: "account:version",
    build: "account:build",
    env: "account:env",
    linkProfile: "account:link-profile",
    linkUsage: "account:link-usage",
    btnSignOut: "account:btn-sign-out",
    btnClearCache: "account:btn-clear-cache",
    signOutSheet: "account:sign-out-sheet",
    clearCacheSheet: "account:clear-cache-sheet",
  },
  profile: {
    screen: "profile:screen",
    fullNameInput: "profile:full-name-input",
    companyNameInput: "profile:company-name-input",
    phoneInput: "profile:phone-input",
    btnSave: "profile:btn-save",
    avatarUploadStub: "profile:avatar-upload-stub",
  },
  usage: {
    screen: "usage:screen",
    summary: "usage:summary",
    summaryReports: "usage:summary-reports",
    summaryInputTokens: "usage:summary-input-tokens",
    summaryOutputTokens: "usage:summary-output-tokens",
    history: "usage:history",
    historyItem: (month: string) => `usage:history-item:${month}`,
    emptyState: "usage:empty-state",
  },
} as const;
