/**
 * Realistic construction site voice notes / typed messages.
 * Messy, informal, with slang, typos, transcription errors,
 * self-corrections, and rambling — just like real field notes.
 */

/** A full day on a commercial build — mixed trades, weather issues, deliveries */
export const COMMERCIAL_BUILD_DAY: string[] = [
  "alright so just got on site its about 6:45, still pretty dark out. weather looks ok for now but theres meant to be rain this arvo",
  "ok so the concreters are already here setting up for the slab pour in zone B. think theres about 6 of them plus the pump truck just rolled in",
  "sparky's not here yet, was supposed to be here at 6:30 to finish the conduit runs before the pour. gonna give him a call",
  "talked to Davo he said the electricians are running 20 mins late, got stuck on the freeway. should be here by 7",
  "just checked the formwork in zone B, looks good, the carpenters did a solid job yesterday. bracing is all tight",
  "oh wait actually theres a bit of a bow in the eastern form near grid line 7. gonna get Tommo to fix that before we pour",
  "Tommo's on it, reckon 15-20 mins to straighten it out. no biggie",
  "the reo in zone B has been signed off by the engineer yesterday so were good to go there once the form is sorted",
  "site temp is about 12 degrees, overcast. wind is pretty calm maybe 5-10 kph from the west",
  "crane operator Johnno is doing his pre-start checks now. we need the crane for lifting the precast panels on level 2 this morning",
  "delivery truck just showed up with the precast panels. 8 panels total, theyre for the north wall level 2",
  "hang on thats not right, its 8 panels for the north AND east walls. 5 north 3 east",
  "sparkies finally here, 4 of them. getting straight into the conduit runs in zone A ground floor",
  "concrete pump is set up and ready. Tommo fixed the formwork. starting the pour now, about 8:15",
  "pour going well, nice and smooth. the mix looks good, 40 MPA as speced",
  "wait no its 32 MPA for the slab, 40 was for the columns last week. yeah 32 is right",
  "plumber just came up to me saying he needs access to zone C for the rough-in but theres materials stacked everywhere. need to get a laborer to clear that out",
  "got Bazza on clearing zone C. should be done by smoko",
  "first precast panel going up now on level 2 north wall. crane working well. Johnno's got it",
  "safety walk with the site manager at 9. he wants to check the edge protection on level 2 before we do the precast lift",
  "edge protection all good. harnesses are being worn by everyone up top. safety nets in place on the south side",
  "the concrete guys are about halfway through the pour now. going to need another truck, the first ones nearly empty",
  "second concrete truck is 15 mins out apparently",
  "ugh just started spitting rain. not heavy but if it picks up we might have to cover the pour",
  "got the tarps ready just in case. the concreters arent worried yet, say its fine for now",
  "smoko break. everyone off site for 15. back at 10:15",
  "ok back from smoko. rain stopped, looking better. suns trying to come out",
  "second concrete truck arrived while we were on break. pour is resuming",
  "3rd precast panel is up now. going good, no issues with the lifts",
  "oh actually the crane had a minor hydraulic leak earlier this morning, Johnno topped up the fluid and its been fine since. should probably log that",
  "the building inspector just showed up unannounced. wants to check the reo and formwork in zone B. told him we already got engineer sign off but hes doing his thing",
  "inspector is happy with everything. no issues. signed off on the pour which is good",
  "lunch time. pour in zone B is about 80% done. should finish by 1:30-2ish",
  "alright back from lunch. pour is nearly done, maybe another 20 minutes",
  "pour is complete. finishing crew is on it, doing the trowel work. looks really good actually",
  "all 5 north wall panels are up now. starting on the east wall panels after lunch I mean after this, its already past lunch lol",
  "got a delivery of timber for the level 2 formwork. 45 lengths of LVL, all 90 by 45. checked them off against the order, all good",
  "actually its 90 by 35 not 90 by 45. my bad. the 45s are coming tomorrow",
  "plumber Bazza finished clearing zone C and Richo's crew is in there now doing the rough-in. 3 plumbers in zone C",
  "the apprentice Dylan dropped a hammer off level 2. hit the exclusion zone barricade below. no one was near it thank god. gave him a talking to about tool lanyards",
  "filed an incident report for the dropped hammer. near miss. Dylan's putting a lanyard on everything now",
  "east wall panels going up now. first one is in, nice and plumb",
  "its getting pretty windy now, gusts maybe 30-35 kph. gonna monitor it, if it hits 40 we'll have to stop the crane lifts",
  "wind has backed off a bit. continuing with the panels",
  "all 3 east wall panels are done. precast is finished for the day. crane is shutting down",
  "the concreters are still finishing the slab surface in zone B. they'll be here till about 3:30 they reckon",
  "sparkies finished the conduit runs in zone A. theyre moving to start the cable pulling tomorrow",
  "afternoon site walkthrough. everything looking pretty good. main things to note are the zone B slab needs to cure, no traffic on it for 24 hours minimum, and zone C plumbing rough-in is about 60% done",
  "Richo says plumbing will be done by midday tomorrow in zone C",
  "end of day. weather held up, no real rain in the end. had about 22 workers on site today total. good productive day. need to order more 12mm reo for next weeks column pours, running low",
  "oh and I need to book the concrete pump again for Thursday for the zone C slab. gonna call them tonight",
];

/** Residential renovation — smaller scale, more informal */
export const RESI_RENOVATION: string[] = [
  "at the house on elm st, just me and Mick today doing the demolition in the kitchen",
  "ripped out all the old cabinets, what a mess. found some asbestos looking stuff behind the splashback",
  "actually I dont think its asbestos, Mick reckons its just old fibro sheeting. but were gonna leave it and get it tested just to be safe. not touching it",
  "called the boss, he's sending a sample to the lab. should know by thursday",
  "we've cleared out most of the kitchen demo. took like 6 skip bins worth of rubble lol. well 2 skip bins but felt like 6",
  "the floor is in rough shape, the old tiles came up but the adhesive is stuck everywhere. gonna need to grind it",
  "hired a floor grinder from Kennards, picking it up tomorrow morning",
  "client wants to keep the original window frame in the kitchen. its hardwood, pretty good condition actually. we'll work around it",
  "found some old knob and tube wiring behind the wall we opened up in the dining room. that all needs to go obviously. sparky is coming wednesday",
  "took a bunch of photos of the wiring situation so the electrician can see what hes dealing with",
  "Mick cut his hand on some sheet metal, not bad but enough to need a bandaid. got the first aid kit from the ute",
  "logged it in the site diary. minor cut, first aid applied, Mick's fine and kept working",
  "weather today is perfect, sunny about 22 degrees. got the windows open airing the place out cos theres heaps of dust",
  "the neighbor came over asking about noise. told her we'll be done with the loud demo stuff by end of week. she was cool about it",
  "wrapped up at about 3. demo is basically done except for the fibro area. waiting on asbestos test results before we touch that wall",
  "tomorrow we'll start framing the new wall layout in the kitchen. Mick's bringing the nail gun",
  "oh also the plumber needs to come look at moving the sink location. the client changed the kitchen layout AGAIN. third time now. whatever",
];

/** Infrastructure / road works — big site, lots of plant */
export const ROAD_WORKS: string[] = [
  "morning. so were on the pacific highway job today, doing the kerb and gutter on the southbound lane from chainage 450 to about 520",
  "traffic control is set up, looks good. two lanes closed, one open with a 40 zone. the TCP was approved last week",
  "weather is absolute rubbish today. been raining since like 4am. the trench is full of water",
  "pumps are running trying to get the water out of the trench. got 2 pumps going, 3 inch and a 4 inch",
  "the excavator operator Steve is on site. CAT 320, been using it to dig the kerb trench. but cant do much till the water is out",
  "surveyor is here pegging out the next section of kerb from chainage 520 to 600",
  "the string line is set up for the first 30 meters of kerb. form work going in now. Kevs crew is on it, 4 guys",
  "concrete truck is booked for 10am but honestly with this rain I dont know if we'll be ready. might have to push to after lunch",
  "called the batch plant, pushed the concrete to 1pm. they were sweet with it",
  "rain has eased off a bit. pumps have got the trench mostly dry. still muddy as hell but workable",
  "the stabilised sand delivery showed up early which is good. 2 truck and dogs, about 40 tonne total. dumped it on the stockpile area",
  "the roller is here too, bomag padfoot for compaction of the sub base. operator Dazza is ready when we need him",
  "laying the sub base material in the first section now. about 100mm depth, well compact it to 98% standard",
  "oh theres been a services issue. telstra pit at chainage 480 that wasnt on the plans. we've hit a conduit. stopping work in that area till we get a location done",
  "called dial before you dig, theyve got a locator coming out this afternoon. pain in the arse",
  "the rest of the kerb prep is going ahead though, just working around the telstra issue",
  "compaction testing on the first section. passed. 99% standard proctor. beauty",
  "lunch. weathers cleared up properly now, even some sun. ground is drying out",
  "locator arrived, confirm there's a telstra conduit running diagonally across our alignment at chainage 478 to 485. its only 300mm deep too. way too shallow",
  "gonna have to get a telstra rep out to discuss relocation or protection. this could delay us a couple days in that section. not ideal",
  "emailed the project manager and the client about the telstra issue. sent photos and the locator report",
  "managed to get the formwork done on the first 30m section despite the dramas. ready for concrete tomorrow if the weather holds",
  "kerb forms look good. Kev checked the string line, everything is within tolerance. grade is spot on",
  "end of day. packed up the traffic control for the night shift to set up their layout. theyre doing line marking on the northbound lanes tonight",
  "total crew today was 8 plus traffic controllers. excavator for 3 hours, roller for 2 hours, 2 x pumps all day. got through it considering the weather and the telstra surprise",
];

/** High-rise concrete pour day — hectic, time-sensitive */
export const HIGHRISE_POUR: string[] = [
  "level 14 column pour today. got 23 columns to do. concrete booked from 6am. lets gooo",
  "first agitator just arrived. 8 cubic metres. starting with the corner columns on grid A1 through A4",
  "pump operator is setting up the line boom on level 14. hose running from the ground floor pump",
  "formwork was checked yesterday but doing a final walk now. checking all the kickers and brace",
  "bracing* autocorrect lol",
  "found one column form on C3 that wasnt fully tied at the base. fixed it. would have leaked everywhere",
  "reo has all been inspected and tagged. engineer was here yesterday. all good on the steel",
  "pour started 6:20. first column done in about 15 mins. using a vibrator to consolidate properly",
  "we're getting into a rhythm now. averaging about 12-15 mins per column with the vibe and topping off",
  "second truck is here, first ones nearly empty. good timing",
  "temp is about 8 degrees this morning. cold. the concrete mix has been adjusted for cold weather curing, the batch plant added accelerator",
  "safety officer doing his rounds. checked that everyone has hard hats, hi vis, steel caps. all good except one of the concreters had cracked safety glasses. gave him a new pair",
  "were up to column 10 now. going well. no issues with the concrete, good slump, flowing nicely into the forms",
  "the slump test on the second truck was 80mm which is within spec. 80 plus or minus 20 so were sweet",
  "oh wait I think the spec says 100 plus minus 20. let me check... yeah its 100 plus minus 20 so 80 is the minimum. just scraped in",
  "actually let me double check that with the engineer. dont want to be borderline on this",
  "engineer confirmed 80 is acceptable for columns. we're good",
  "12 columns done by 9:30. smoko",
  "the pump blocked up after smoko. took about 20 mins to clear it. was a rock or something in the line",
  "back pouring now. lost a bit of time but should still finish today no worries",
  "we're getting some bleed water on the columns we poured first. thats normal for this mix in cold weather. will re-vibrate and top off later",
  "truck 4 just arrived. ordering truck 5 for after lunch",
  "some of the formwork bolts on D2 column look a bit rusty. I mean the form ties not the bolts. theyre functional still but should probably replace them for next pour",
  "20 columns done. 3 to go. last truck should cover it",
  "and done! all 23 columns poured by 2:15pm. finishing up the tops now, troweling smooth",
  "gonna set up the curing compound spray once the surface has firmed up a bit. probably in an hour or so",
  "cylinders taken, 6 test cylinders from todays pour. labeled and in the curing box. 7 day and 28 day breaks",
  "stripping the columns can happen thursday arvo, engineer wants 48 hours minimum cure before we strip. that takes us to thursday 2pm",
  "good day, no safety issues, no concrete rejects, all columns done. onto the level 14 slab formwork tomorrow",
];

/** Fitout / interior works — finishing stage */
export const INTERIOR_FITOUT: string[] = [
  "level 3 fitout for the office tenancy. the plasterers are finishing the last of the cornices today",
  "painters started on level 2. doing the primer coat on all the plasterboard. 3 painters, they reckon 2 days for primer on the whole floor",
  "carpet tiles were delivered. 180 square meters worth. they look right, checked against the spec sheet. colour is Dulux Warm Grey or whatever the code is",
  "actually the carpet tile colour is called 'Fossil' according to the box. matches the sample the architect approved so all good",
  "the joiner is here measuring up for the reception desk. custom job, hes taking final measurements before fabrication. should be ready to install in 2 weeks",
  "fire services guys are here installing the sprinkler heads on level 3. 4 of them, been going since 7. theyre about half done on this floor",
  "theres a clash between the sprinkler head location and the air con diffuser at grid D5. HVAC guys and fire guys need to sort it out",
  "got them both together, they worked out the diffuser can move 200mm to the east. fire sprinkler stays where it is because of the coverage requirement. easy fix",
  "the electrician is doing the final fix on level 2. power points, light switches, data points. theres a lot of em",
  "data cabling guys finished pulling cables yesterday. 86 data points on level 2 alone. all cat6A",
  "the clients IT guy is coming friday to do the testing and certification on the data cables",
  "ceiling grid is going in on level 3. the ceiling guys are pretty quick, they'll probably finish this floor by end of tomorrow",
  "found a damaged ceiling tile in the box, one of the edges is chipped. pulled it out. we've got spares so no drama",
  "the kitchen joinery was installed yesterday on level 2 but the benchtop has a chip on the front edge. flagged it with the joiner, he's ordering a replacement benchtop",
  "door hardware is being installed today. lever handles, closers, all the commercial grade stuff. theres 34 doors on this floor",
  "one of the door frames on the meeting room is out of plumb by about 5mm. the chippy is going to pack it out and re-fix the architrave",
  "signage guys are here measuring for the building directory and the floor number signs",
  "cleaned up level 2 for the clients walkthrough tomorrow. vacuumed, wiped down all surfaces. looks pretty sharp",
  "made a snag list from my walkthrough. about 15 items. mostly minor stuff. paint touch ups, a couple of switches that are crooked, one power point that doesnt work",
  "emailed the snag list to all the subbies. gave them till friday to close everything out before the client sees it next week",
];

/** Quick weather + basic site check — some days are quiet */
export const QUIET_DAY: string[] = [
  "not much happening today. waiting on materials mostly",
  "weathers nice though. sunny 24 degrees no wind",
  "just me and one laborer on site doing cleanup and prep for next week",
  "swept out the ground floor, stacked the offcuts into the skip",
  "the safety mesh on the west scaffolding has come loose. tied it back up properly",
  "checked all the fire extinguishers, they're in date. all 4 on the ground floor and 2 on level 1",
  "took some progress photos for the client update. north elevation south elevation and the car park area",
  "material delivery tomorrow morning. 3 pallets of bricks, should arrive by 8. need to make sure theres space near the laydown area",
  "cleared the laydown area and put up some witches hats so the truck driver knows where to drop em",
];

/** Voice notes with lots of transcription errors and corrections */
export const MESSY_TRANSCRIPTION: string[] = [
  "ok so the excavator just went through AH wait no not through a pipe, NEAR the pipe, the storm water pipe near grid F6. didn't hit it but it was close, maybe 100 mils away",
  "the plaster is applied in the lounge room looks terrible honestly theres like 3 or 4 patches where you can see the joints showing through. gonna need to be sanded back and recoated",
  "too much slab waiting i mean two months waiting on the slab reinforcement from the supplier theyve been saying next week for three weeks now",
  "the die electric the DIELECTRIC union for the hot water system hasnt been installed which means the copper and steel are touching directly gonna get corrosion there for sure. told the plumber to fix it",
  "crane is down today, matenance maintenance, think its the slew ring bearings or something. mechanic reckons back up tomorrow",
  "just measured the window opening on the north wall and its 10 mil out of square. within tollerance tolerance but only just. the window guys should be able to shim it",
  "delivery of the I dont even know what theyre called those bracket things for the the uh facade cladding support brackets thats it. anyway they showed up and theyre the wrong size. supposed to be 150mm and these are 100mm. rejected the delivery sent them back",
  "waterproof membrane on the bathroom floor looks good BUT they didnt take it up the wall high enough. code says 150mm above finished floor level and this looks like maybe 100 at best. flagged it, they're coming back",
  "scaff guys are here erecting the scaffold on the east side of the building. should take em most of the day. 4 bays wide and going up to level 3 so thats about 9 meters high",
  "the new apprentice is alright actually. hes keen, shows up on time, asks questions. been getting him to do the site cleanup and basic measurements. names Jake I think. or Jack. one of those",
  "sorry about the background noise theres a jackhammer going right behind me. ANYWAY the point is the structural steel for the mezzanine floor has arrived and its being unloaded now. about 15 members total including the main beams and the secondary purlins",
];

/** A rambling long-winded note-taker who puts everything in one or two messages */
export const RAMBLING_NOTES: string[] = [
  "so look I've been walking around the site for the last hour and heres kinda where everythings at right, so first off the brickies are going great guns on the east wall theyre about 2 thirds of the way up to plate height which is good cos the roof trusses are coming next wednesday and we need that wall done by then, Davo reckons theyll be done monday and I believe him cos his crew has been smashing it, theyve got 4 guys on it and theyre laying about 400 bricks a day each which is solid, anyway the mortar colour looks consistent which is good cos on the last job they had that issue where some batches were lighter than others and the client had a fit",
  "the other thing is the plumber Richo has roughed in all the sewer and stormwater under the slab in zone A but theres a problem with the fall on one of the stormwater lines, its only got like 1 in 150 fall and the spec says 1 in 100 minimum, I told him about it and he said he'll fix it this arvo but between you and me I think he knew about it and was hoping nobody would notice, anyway I took a photo of the level on the pipe so we've got a record in case it comes up at inspection",
  "oh and also I nearly forgot the client Sarah came by this morning with her interior designer and they spent about an hour looking at the bathroom tile layout, long story short they want to change the feature wall from the herringbone pattern to a straight stack bond pattern which doesnt really affect us much structurally or anything but it does mean the tiler needs new setting out marks and the waterproofer might need to come back because the niche locations are changing by about 200mm. I said any changes need to be in writing and she said shell email through a variation request by end of day. we'll see.",
  "last thing, the skip bin is overflowing again. I've called the waste company three times this week and they keep saying tomorrow. if they dont pick it up by friday I'm calling someone else. its a OH&S issue having rubbish piling up around the bin. also theres some broken glass near the site entry that needs to be cleaned up before someone drives over it. getting the laborer onto it now.",
];

/** Notes that include specific measurements and technical details */
export const TECHNICAL_NOTES: string[] = [
  "got the compaction test results back from the geotech. first layer at 300 mil depth came in at 97 percent MDD and the second layer at 150 came in at 101 percent. both pass the minimum 95 so were good",
  "concrete spec for tomorrows pour is 40 MPA at 28 days, 120 slump, 20 mil aggregate, S40 exposure class. batch plant confirmed the mix design so we're all set there",
  "checked the steel delivery against the schedule. 16 N16 bars at 6 metres, 24 N12 bars also at 6 metres, and 45 N12 ligatures at 300 centres. all matches up, mill certs are in the folder",
  "went through the window schedule for level 1. windows 1 through 8 are all 2100 by 1200 awning type, and windows 9 and 10 are the smaller highlight ones 1800 by 600. all aluminium powdercoat in monument colour",
  "the stormwater pipe is 150 mil PVC SN8 class, laid at 1 in 80 fall running towards the junction pit on the north east corner. pipe covers sitting at 450 mil which is above the 300 minimum so thats fine",
  "slab is 200 mil thick with N12 reo at 200 centres each way top and bottom. engineers checked the reo yesterday and tagged it off. mesh chairs at 1200 centres holding up the top mat",
  "checked the structural steel connection on column B3 to beam BM-04. six M20 bolts 8.8 grade per connection, all torqued to 340 newton metres as per the engineers spec. torque marks are all done and painted",
];

/** Heavy focus on materials received, used, wasted, and on-order */
export const MATERIALS_HEAVY_DAY: string[] = [
  "big delivery day today. first truck arrived 6:30 with 4 pallets of common bricks, about 500 per pallet so 2000 bricks total. checked the delivery docket matches our PO, all good",
  "second delivery at 7:15, timber framing package from Bowens. 60 lengths of 90 by 45 MGP10 at 4.8 metres, 30 lengths of 90 by 35 MGP10 at 3.6 metres, and 20 sheets of 15 mil plywood for bracing. counted them all off the truck, correct quantities",
  "theres also 2 packs of truss nail plates in that delivery. 200 plates per pack. stored them in the container cos they'll rust if they get wet",
  "oh the plywood has some water damage on like 3 sheets. the plastic wrap was torn on the top of the pack. gonna use those ones for temporary bracing not permanent. noted it on the delivery docket and took photos",
  "brickies used about 600 bricks today plus 15 bags of mortar mix. we started the day with 40 bags of mortar so we've got 25 left. need to reorder, gonna need at least another 50 bags for next week",
  "the sand pile is getting low too. probably only 2 cubic metres left. need a delivery of brickies sand, the washed stuff not the yellow rubbish we got last time",
  "electrician used 3 rolls of 2.5mm TPS cable today running circuits on level 1. hes got maybe 1 and a half rolls left from the original order of 10 rolls. need to reorder cable",
  "also the sparky needs more 20mm conduit. used about 40 lengths of the 4m sticks this week. ordering another bundle of 50",
  "plumber brought his own materials today. 50m of 100mm PVC DWV pipe, about 30 fittings various types, glue and primer. his stuff not ours",
  "reo delivery confirmed for tomorrow morning. 2 tonnes of N12 bar and 500kg of N16 bar. also 50 ligature sets for the column cages. got the mill certs emailed through already",
  "we burned through heaps of screws today with the framing. used probably 4 boxes of 75mm batten screws. only 2 boxes left on the shelf. adding to the order list",
  "the render sand that was delivered yesterday is the wrong grade. ordered M classification but they sent U classification. way too coarse for the finish coat. called the supplier, theyre picking it up tomorrow and replacing it. in the meantime the renderers cant do the top coat, only the scratch coat",
  "concrete sealer arrived. 4 drums of Duram Duraseal, 20 litres each. thats enough for the ground floor slab and the driveway. stored in the hazmat cage",
  "waterproofing membrane rolls delivered. 6 rolls of Ardex WPM 300, each roll is 20m x 1m. need 5 rolls for the bathrooms and laundry so we've got 1 spare which is handy",
  "we're completely out of 75mm nails for the framing gun. borrowed a box off the chippy next door but need to get our own supply sorted. ordered 5 boxes from the trade store, should arrive tomorrow on the morning run",
  "roof tiles were delivered this arvo. 28 pallets of Monier concrete tiles, terracotta colour. thats the full amount for the whole roof. stacked em in the car park area with plastic over the top",
  "counted the DPC (damp proof course) rolls. got 6 rolls left which should be enough for the remaining walls. each roll is 30m and we've got about 150 lineal metres of wall left so yeah should be fine",
  "waste today: about half a skip of timber offcuts, a bucket of bent nails, and a few cracked bricks. not bad actually, pretty minimal waste compared to last week",
];

/** Focused on equipment usage, hours, breakdowns, and movements */
export const EQUIPMENT_HEAVY_DAY: string[] = [
  "plant on site today: 13 tonne excavator the cat 313, the 3 tonne cat vibe roller, and the bobcat S70 skid steer. all three started at 7am",
  "the excavator did the bulk excavation in zone D from 7 to 11. Steve operating. moved about 200 cubic metres of clay. running well no issues",
  "after lunch Steve switched the bucket on the excavator to the 450mm trenching bucket for the stormwater trench. took about 20 mins to swap over",
  "excavator was trenching from 12:30 to 3:30. about 60 lineal metres of trench at 600mm deep. good progress",
  "total excavator hours today: 7.5 hours operating time. fuel was about three quarters at start of day, down to just under half now. will need a diesel top up tomorrow",
  "the roller was compacting the fill in zone C. Dazza operating from 7am to 2pm. 7 hours on the roller today. did 4 passes over the whole area like the geotech said",
  "roller broke down at about 2pm. the vibration mechanism stopped working mid pass. Dazza says it feels like the belt. called the hire company and theyve got a mechanic coming first thing tomorrow",
  "so the roller is parked up near the site shed. out of action till the mechanic looks at it. hope its just the belt cos if its the exciter bearing were looking at a few days without it",
  "the bobcat was on all day, loading spoil from the excavation into trucks. Bluey operating. ran from 7am to 3:30pm so thats 8.5 hours",
  "bobcat needs new tyres soon by the way. front rights are pretty bald. mentioned it to the boss, he said end of the week at the latest",
  "we had 4 tip trucks running spoil to the dump today. all subbied out to Martins Haulage. each truck doing about 5 loads, 10 cubic metres per load so roughly 200 cubes carted off site total. matches what the excavator dug which is good",
  "concrete pump came on site at 6am for the zone B pour, 42 metre boom pump from Schwing. set up took about 45 mins. pumped for 3 hours straight then packed up by 10:30. total on site about 4.5 hours",
  "the pump had a minor blockage around 8:15, took 10 mins to clear. operator said the mix was a bit dry on that load. second truck was better",
  "tower crane log: 14 lifts today. mostly precast panels and reo cages. no downtime, Johnno kept it moving all day. crane operated from 7am to 3pm, 8 hours",
  "the generator has been running 24/7 for the curing lights on level 2. checked the fuel, topped it up with 40 litres of diesel. should last another 2 days",
  "scaffold: the scaffolders brought a 10 tonne truck with all their gear. erected 6 bays on the east elevation today, about 18 metres long and 12 metres high. took 4 blokes 7 hours. theyll be back tomorrow to do the returns on the north and south ends",
  "the compressor for the nail guns was playing up this morning, kept cutting out. turned out the air filter was clogged with dust. cleaned it out and its been fine since. need to add compressor filter to the weekly maintenance checklist",
  "hired a 7kva generator from Coates for the electricians working in zone E where theres no permanent power yet. picked it up this morning, $95 a day. should need it for the rest of the week",
  "forklift was on site for the material deliveries. used it from 7 to 9am unloading trucks then again from 1 to 2pm for the afternoon delivery. total about 3 hours use today",
];

/** A day with lots of different deliveries and material tracking */
export const DELIVERY_TRACKING_DAY: string[] = [
  "first truck just arrived, 7 oh 5. Hanson concrete, 6 cubes of 32 MPA with 100 slump. docket number is H 445821. driver was Pete",
  "second concrete truck rolling in now at 7:20. another 6 cubes same spec. docket is H 445822",
  "third and final concrete truck for the morning pour. quarter to 8. 4 cubes this time. docket H 445823. so thats 16 cubes total which is spot on what we ordered",
  "Boral timber truck showed up at 8:30. 2 packs of 90 by 45 H2 treated pine, 100 lengths total at 5.4 metres. delivery note is BT 98234. all straight no rejects",
  "plumbing supplies from Reece arrived about quarter past 9. 30 metres of 15 mil copper pipe, 20 metres of 20 mil copper, box of assorted fittings, and 2 Rinnai hot water units. checked against the order and one fitting pack is missing. we ordered 3 packs of 15 mil elbows and only got 2. called Reece theyre sending the missing pack this arvo",
  "the missing elbow pack from Reece arrived at 2pm. all sorted now",
  "steel arrived from OneSteel at 10. 3 tonne of reo bar, mix of N12 N16 and N20. all tagged with heat numbers matching the mill certs. unloaded it with the crane into the reo laydown area",
  "insulation batts from Fletcher at 11:30. 40 packs of R2.5 wall batts and 20 packs of R4.0 ceiling batts. stored em in the container to keep dry. thats the full insulation order for the whole job which is good",
  "brickworks truck at 1pm. 6 pallets of face bricks PGH dry pressed in Limestone. about 480 per pallet so just under 3000 bricks. we only ordered 2500 so weve got a few hundred spare which is fine, better too many than too few",
  "electrical gear from Middys at half 2. 5 rolls of 2.5 mil TPS, 5 rolls of 1.5 mil TPS, 3 switchboards, about 80 GPOs, 40 light switches, and a box of miscellaneous bits. the sparky checked it all says its complete",
  "roofing materials from Stratco at 3. 35 sheets of custom orb colorbond in monument colour, each sheet is 6 metres long. also 4 boxes of roofing screws and 2 rolls of sisalation. all looks good. stacked the sheets on bearers off the ground with the protective film still on",
  "rejected delivery: a pallet of tiles showed up from Beaumont tiles but nobody ordered them. wrong site. sent the driver away. not our problem",
  "running total of materials on site now: we've got enough bricks for about 2 more weeks, enough timber to frame level 1 completely, full insulation order stored, full electrical rough-in materials, and roofing materials ready to go once framing is done",
  "materials we still need to order: guttering and downpipes, external cladding, internal plasterboard, doors and frames, and all the finishing hardware. the PM is sorting the orders this week",
];

/** Plant and equipment focused — multi-trade day with lots of machines */
export const PLANT_INTENSIVE_DAY: string[] = [
  "big day for plant today. running 6 machines plus trucks. heres the rundown",
  "so first up the 20 tonne excavator, CAT 320, Steves on it. started at 6:30 doing the basement dig in zone A. burning through diesel this things thirsty. filled it up last night, 200 litre tank",
  "then we got the 8 tonne Kubota KX080, Mick operating. hes on the eastern trench work from 7. smaller machine works better in the tight areas near the boundary",
  "the bobcat skid steer S650, Bluey operating. hes loading trucks all morning from the stockpile. switched to the pallet forks after lunch to move materials around",
  "the 12 tonne smooth drum roller HAMM HD12, Dazza operating for the driveway sub base compaction. only needed from 9 to 12. 3 hours. compaction tests passed first go",
  "got the mobile crane in this arvo, 25 tonne Franna AT-22. lifting the steel beams into the basement. 4 lifts total, heaviest was the main portal frame at 3.2 tonnes. crane on site from 1 to 4, 3 hours",
  "and the concrete pump, 36 metre boom from Bills Concrete Pumping. just for the retaining wall pour this morning. on site 7 to 10, 3 hours. pumped 18 cubic metres total",
  "trucks: 3 tip trucks carting spoil to the tip. Ryans Transport. averaging 6 loads each today. spoil going to the approved dump site on Johnson Rd",
  "the 20 tonne excavator had a track tension issue around 10am. Steve adjusted it himself, took about 30 mins. said its been a bit loose for a few days. might need the mechanic to look at it properly on the weekend",
  "the Kubota was down for about 45 mins after lunch. hydraulic hose blew on the dipper arm. lucky Mick had a spare hose in his toolbox, old school. got it swapped out and back running",
  "the bobcat attachment swap from bucket to forks took about 15 mins around 12:30. also swapped back to bucket at 3pm for the last hour of cleanup. so two changeovers today about 15 mins each",
  "end of day plant hours summary: CAT 320 did 8 hours, Kubota did 7 hours minus the 45 min breakdown so call it 6.25 productive hours, bobcat did 8 hours, roller 3 hours, crane 3 hours, pump 3 hours",
  "all machines shut down and locked. keys in the site office. excavators parked in the dig area, bobcat near the shed, roller near the driveway",
  "fuel situation: the 20 tonne needs a fill tomorrow for sure. the kubota is about half. bobcat is fine. gonna call the diesel supplier to bring the fuel truck out in the morning. need at least 300 litres",
  "the hired roller is due back to Coates on Friday. only needed it for the driveway compaction. thats done now so might return it tomorrow if the boss is happy to save a days hire. at $380 a day its not cheap",
  "crane hire invoice will be 3 hours minimum plus mob/demob. Franna quote was $180/hr plus $450 mob. so roughly $990 for today. worth it though, no way we could have lifted those beams by hand",
];

/** Materials wastage and quality issues */
export const MATERIALS_QUALITY_ISSUES: string[] = [
  "the ready mix concrete on the second truck was way too wet. slump test came in at 180mm and the spec is 100 plus minus 20. told the driver to take it back. wasted an hour waiting for a replacement truck",
  "replacement concrete arrived at 10:30. tested at 95mm slump. perfect. no more issues with the rest of the pour",
  "the timber we got from the supplier last week has heaps of splits and warping. counted 14 lengths out of 60 that are basically unusable. thats nearly 25% reject rate which is rubbish. called the supplier to complain and get replacements",
  "bricks on the south pallet have some efflorescence, that white salty looking stuff. brickies reckon its cosmetic and will wash off after the first few rains. keeping an eye on it",
  "the waterproofing membrane roll number 4 had a tear in it about 2 metres in. probably damaged in transit. cut out the damaged section and used the rest. we've got that spare roll so no delay",
  "paint colour for the external walls doesnt match the sample. the spec says Dulux Domino but what was delivered looks more like a dark grey than black. checked the tin labels, its actually Dulux Domino which is correct. might just be the light in here. letting it dry and will check tomorrow in natural light",
  "the floor tiles for bathroom 2 are NOT the ones the client picked. these are 300 by 300 and the spec says 600 by 600. someone at the tile shop mixed up the order. sending them back tomorrow. this delays the tiler by at least 3 days while we wait for the right ones",
  "reo mesh delivered today has some surface rust. the engineer said light surface rust is acceptable per the AS standard as long as its not flaking or pitting. gave it the thumbs up. used it for the pathway slab",
  "we've been tracking wastage this week. timber offcuts: about 0.5 cubic metres in the skip. brick breakage: approximately 80 bricks broken or chipped, roughly 4% of what we laid. concrete: we ordered 16 cubes and used 15.2, so 0.8 cube waste which is about 5%. all within normal ranges the PM says",
  "the adhesive for the floor tiles was past its expiry date. the tiler spotted it thankfully. use by date was January 2026 and we're in March. chucked the 3 expired bags and using the newer stock. need to do better with the first in first out rotation in the storage container",
  "door frames delivered have the wrong hinge rebate. they're set up for left hand doors but we need right hand for the ensuite and WIR. 4 frames affected. supplier is swapping them out friday",
];

/** Warehouse / industrial build with heavy steel and equipment */
export const WAREHOUSE_BUILD: string[] = [
  "portal frame erection day on the warehouse. the steel crew from AusFab is here. 8 guys plus the dogman and crane operator",
  "mobile crane is a 50 tonner, Liebherr LTM. massive thing. took about an hour to set up the outriggers and boom",
  "first portal frame going up now. each frame is about 12m span, 6m to the apex. columns are 310UC97 and the rafters are 460UB67. heavy gear",
  "materials on site for today: 6 portal frames complete with haunches, 24 x M20 base plate bolts per column so thats 288 bolts total, plus the apex and knee connection bolts probably another 200 bolts. all 8.8 grade galvanised",
  "also got 48 lengths of C20024 purlins stacked up ready to go once the frames are up. each purlin is 8m long. theyll span between the portal frames at 1200 centres",
  "crane is making good lifts. first 2 frames up and plumbed by 10am. the steel guys are quick",
  "temporary bracing cables are on the first 2 frames to stop them falling over before the purlins tie them together. safety first",
  "delivery of roofing at 11am. 32 sheets of trimdek colorbond in surfmist, each one is 9.5m long custom cut to length. plus 16 sheets of wall cladding at 6m. fascia, barge capping, 8 boxes of tek screws, and a heap of rivets",
  "stacking the roofing sheets was a pain cos theyre so long. 9.5 meters is awkward. used the forklift with extended tines and 3 guys guiding",
  "4 frames up by lunch. halfway. crane hasnt missed a beat. operator reckons its a good day for lifts, not too windy",
  "after lunch we had a slight drama, one of the base plate bolt holes didnt line up on frame 5 column A side. about 6mm out. the steel guys drilled it out to the next bolt size up with a mag drill. engineer on the phone approved using M24 bolts in those 2 holes instead of M20. not ideal but structurally fine",
  "all 6 frames up by 3pm. started on the purlins. got about 16 of the 48 purlins on before knock off time",
  "equipment hours today: 50t crane from 6:30am to 3:30pm, 9 hours. forklift intermittent throughout the day maybe 4 hours total. EWP cherry picker for the purlin work from 1pm to 4pm, 3 hours",
  "material usage: all 6 frames erected. roughly 280 of the 288 base plate bolts used (8 spares). 16 of 48 purlins installed. all temporary bracing cables deployed. no material rejects or waste worth noting",
  "the dog man Barry did a great job today. every lift was smooth, good communication with the crane operator on the two way. no near misses or safety issues",
  "steel crew back tomorrow to finish purlins and start on the girts. roofing crew starts thursday if the purlins are done. should be tight but doable",
];

/** Earthworks site — all about dirt, trucks, and compaction equipment */
export const EARTHWORKS_DAY: string[] = [
  "earthworks in full swing today on the subdivision. pad prep for lots 14 through 20",
  "running 2 excavators: the 30 tonne Hitachi ZX300 on the main cut and the 14 tonne CAT 314 on the service trenches. both started at 6am",
  "also got the D6 dozer pushing material from the cut to the fill areas on the western lots. Thommo operating",
  "8 truck and dogs running today carting fill from the borrow pit on Smiths farm. each one carries about 16 cubic metres so thats 128 cubes per round trip across all trucks. theyre averaging 4 trips each today so roughly 500 cubic metres of fill delivered",
  "the fill material is a sandy clay, tested and approved by the geotech last week. moisture content is pretty close to optimum which is good given we havent had rain for a week",
  "the 18 tonne padfoot roller is doing the compaction on lot 14. 4 passes at 300mm layers as per the spec. Dazzas been on the roller since 7",
  "geotech is on site doing density tests. hes done 3 tests so far on lot 14: test 1 was 96% MDD, test 2 was 98%, test 3 was 97%. all pass the 95% minimum. nice one",
  "the water cart has been going non stop keeping the dust down and conditioning the fill. 10,000 litre cart, Kevvo driving. hes refilled it twice already today from the hydrant on the corner",
  "fuel truck came at lunch time. filled up the 30 tonne excavator (350 litres), the 14 tonne (150 litres), the dozer (200 litres), and topped up the roller (80 litres). also filled the water cart. total diesel delivery was about 900 litres",
  "we've moved approximately 800 cubic metres of material today between the cut, fill, and imported material. surveyor checked the levels on lot 14 and 15, both within 20mm of design which is spot on",
  "the grader came on this afternoon for 2 hours to trim the road formation on the new internal road. operator Johno has a good eye, got it looking perfectly flat. the road base goes on next week",
  "end of day equipment summary: Hitachi 30t excavator 9 hours, CAT 14t excavator 8 hours, D6 dozer 8 hours, padfoot roller 7 hours, grader 2 hours, water cart 9 hours. 8 tip trucks averaging 7 hours each. no breakdowns today which is a bloody miracle on this job",
  "materials consumed: approximately 500 cubic metres of imported fill, about 900 litres of diesel, and probably 30,000 litres of water between dust suppression and compaction conditioning",
  "surveyor pegged out lots 16 and 17 ready for tomorrow. the cut on lot 16 is gonna be about 1.5m deep so a fair bit of material to shift. dozer and the 30 tonner will handle it",
];
